/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jmultigwas;

import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author lg
 */
public class ViewToolBar extends javax.swing.JPanel {
    Controller controller;

    public ViewToolBar(Controller controller) {
        this.controller = controller;        
        initComponents();
        radioButtonAdditiveGA.setActionCommand("Additive");
        radioButtonDominantGA.setActionCommand("Dominant");
        radioButtonAllGA.setActionCommand("All");
    }
    
    public void setTestMode (boolean testMode) {
        if (testMode) {
            cboxGapit.setSelected (false);
            cboxShesis.setSelected (false);
            cboxTassel.setSelected (false);
        }
    }
    
    public String getToolsToRun () {
        String tools = "";
        if (cboxGwaspoly.isSelected())
                tools += "GWASpoly ";
        if (cboxShesis.isSelected())
                tools += "SHEsis ";
        if (cboxGapit.isSelected())
                tools += "GAPIT ";
        if (cboxTassel.isSelected())
                tools += "TASSEL ";
        return (tools);
    }
    
    public String getGeneAction () {
        String selection = this.buttonGroupGeneAction.getSelection().getActionCommand();
        return (selection);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator7 = new javax.swing.JSeparator();
        buttonGroupGeneAction = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        panelToolBar = new javax.swing.JPanel();
        panelTools = new javax.swing.JPanel();
        panelTetra = new javax.swing.JPanel();
        labelTools = new javax.swing.JLabel();
        subpanelTools = new javax.swing.JPanel();
        cboxGwaspoly = new javax.swing.JCheckBox();
        cboxShesis = new javax.swing.JCheckBox();
        cboxGapit = new javax.swing.JCheckBox();
        cboxTassel = new javax.swing.JCheckBox();
        panelGeneAction = new javax.swing.JPanel();
        labelGeneAction = new javax.swing.JLabel();
        subpanelGeneAction = new javax.swing.JPanel();
        radioButtonAdditiveGA = new javax.swing.JRadioButton();
        radioButtonDominantGA = new javax.swing.JRadioButton();
        radioButtonAllGA = new javax.swing.JRadioButton();
        panelRun = new javax.swing.JPanel();
        buttonRun = new javax.swing.JButton();
        labelMultiGWAS = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setLayout(new java.awt.CardLayout());

        jToolBar1.setBackground(new java.awt.Color(153, 255, 153));
        jToolBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setPreferredSize(new java.awt.Dimension(155, 50));

        panelToolBar.setPreferredSize(new java.awt.Dimension(150, 140));
        panelToolBar.setRequestFocusEnabled(false);
        panelToolBar.setLayout(new java.awt.BorderLayout());

        panelTools.setPreferredSize(new java.awt.Dimension(150, 120));
        panelTools.setRequestFocusEnabled(false);
        panelTools.setLayout(new java.awt.GridLayout(5, 0));

        panelTetra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelTetra.setLayout(new java.awt.BorderLayout());

        labelTools.setBackground(java.awt.Color.green);
        labelTools.setText("GWAS tools:");
        labelTools.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelTools.setOpaque(true);
        panelTetra.add(labelTools, java.awt.BorderLayout.PAGE_START);

        subpanelTools.setLayout(new java.awt.GridLayout(4, 0));

        cboxGwaspoly.setSelected(true);
        cboxGwaspoly.setText("GWASpoly");
        subpanelTools.add(cboxGwaspoly);

        cboxShesis.setSelected(true);
        cboxShesis.setText("SHEsis");
        subpanelTools.add(cboxShesis);

        cboxGapit.setSelected(true);
        cboxGapit.setText("GAPIT");
        subpanelTools.add(cboxGapit);

        cboxTassel.setSelected(true);
        cboxTassel.setText("TASSEL");
        subpanelTools.add(cboxTassel);

        panelTetra.add(subpanelTools, java.awt.BorderLayout.CENTER);

        panelTools.add(panelTetra);

        panelGeneAction.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGeneAction.setLayout(new java.awt.BorderLayout());

        labelGeneAction.setBackground(java.awt.Color.green);
        labelGeneAction.setText("Gene action models:");
        labelGeneAction.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelGeneAction.setOpaque(true);
        panelGeneAction.add(labelGeneAction, java.awt.BorderLayout.PAGE_START);

        subpanelGeneAction.setLayout(new java.awt.GridLayout(4, 0));

        buttonGroupGeneAction.add(radioButtonAdditiveGA);
        radioButtonAdditiveGA.setSelected(true);
        radioButtonAdditiveGA.setText("Additive");
        radioButtonAdditiveGA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonAdditiveGAActionPerformed(evt);
            }
        });
        subpanelGeneAction.add(radioButtonAdditiveGA);

        buttonGroupGeneAction.add(radioButtonDominantGA);
        radioButtonDominantGA.setText("Dominant");
        subpanelGeneAction.add(radioButtonDominantGA);

        buttonGroupGeneAction.add(radioButtonAllGA);
        radioButtonAllGA.setText("All");
        subpanelGeneAction.add(radioButtonAllGA);

        panelGeneAction.add(subpanelGeneAction, java.awt.BorderLayout.CENTER);

        panelTools.add(panelGeneAction);

        panelRun.setLayout(null);

        buttonRun.setForeground(new java.awt.Color(255, 102, 102));
        buttonRun.setText("Run");
        buttonRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRunActionPerformed(evt);
            }
        });
        panelRun.add(buttonRun);
        buttonRun.setBounds(40, 40, 70, 25);

        panelTools.add(panelRun);

        panelToolBar.add(panelTools, java.awt.BorderLayout.CENTER);

        labelMultiGWAS.setBackground(new java.awt.Color(102, 0, 153));
        labelMultiGWAS.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelMultiGWAS.setForeground(java.awt.Color.yellow);
        labelMultiGWAS.setText("MultiGWAS 1.0");
        labelMultiGWAS.setOpaque(true);
        labelMultiGWAS.setPreferredSize(new java.awt.Dimension(82, 55));
        labelMultiGWAS.setRequestFocusEnabled(false);
        panelToolBar.add(labelMultiGWAS, java.awt.BorderLayout.PAGE_START);

        jToolBar1.add(panelToolBar);

        add(jToolBar1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRunActionPerformed
        // TODO add your handling code here:
        controller.onRunApplication();
    }//GEN-LAST:event_buttonRunActionPerformed

    private void radioButtonAdditiveGAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonAdditiveGAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonAdditiveGAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupGeneAction;
    private javax.swing.JButton buttonRun;
    private javax.swing.JCheckBox cboxGapit;
    private javax.swing.JCheckBox cboxGwaspoly;
    private javax.swing.JCheckBox cboxShesis;
    private javax.swing.JCheckBox cboxTassel;
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel labelGeneAction;
    private javax.swing.JLabel labelMultiGWAS;
    private javax.swing.JLabel labelTools;
    private javax.swing.JPanel panelGeneAction;
    private javax.swing.JPanel panelRun;
    private javax.swing.JPanel panelTetra;
    private javax.swing.JPanel panelToolBar;
    private javax.swing.JPanel panelTools;
    private javax.swing.JRadioButton radioButtonAdditiveGA;
    private javax.swing.JRadioButton radioButtonAllGA;
    private javax.swing.JRadioButton radioButtonDominantGA;
    private javax.swing.JPanel subpanelGeneAction;
    private javax.swing.JPanel subpanelTools;
    // End of variables declaration//GEN-END:variables
}
